# -*- mode: ruby -*-
# vi: set ft=ruby :

# Mit diesem Vagrant File wird eine Virtuelle Maschine erstellt welche eine Datenbank hat und vom Host aus via MySQL Workbench erreicht 
# werden kann. Diese Virtuelle Maschine hat eine Firewall und weitere Security Features. 

# Virtuelle Maschine mit Datenbank
Vagrant.configure("2") do |config|

  # Mit "ubuntu/bionic64" wird eine Ubuntu 18.04 64 Bit Virtuelle Maschine erstellt
  config.vm.box = "ubuntu/bionic64"

  # Mit der Zeile wird der Hostname der VM festgelegt
  config.vm.hostname = "m300lb2"

  # Hier wird Virtualbox als Provider für die Virtuelle Maschine definiert, das heisst das die Virtuelle Maschine auf Virtualbox läuft
  config.vm.provider "virtualbox" do |vb|

    # Hier wird die Kapazität des RAMs der Virtuellen Maschine definiert, in diesem Fall ist diese 2048MB gross
    vb.memory = "2048" 
    
    # Hier wird der Name der VM definiert 
    vb.name = "m300lb2"

  end

  # Hier in dieser Zeile wird definiert das ein Shell Script/Config File verwendet wird von der Vagrant Box namens config.sh
  config.vm.provision "shell", path: "config.sh"

  # Hier wird die IP Adresse der Virtuellen Maschine definiert
  config.vm.network "private_network", ip: "192.168.55.200"

end

