version: '2.2'
services:
  postgresql:
    image: 'bitnami/postgresql:11'
    mem_limit: 512M
    mem_reservation: 128M
    cpus: 0.25
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - POSTGRESQL_USERNAME=bn_redmine
      - POSTGRESQL_DATABASE=bitnami_redmine
    volumes:
      - 'postgresql_data:/bitnami/postgresql'
